// /utils/persistTasks.utils.js

import  pool  from "../config/db.js";
import { v4 as uuidv4 } from "uuid";

/**
 * persistTasks
 * @param {Array} tasks - Flattened tasks from validator
 * @param {Object} userProfile - User from DB
 * @param {Object} aiSnapshot - Raw AI JSON output
 * @returns {Object} { roadmap_id, message }
 */
async function persistTasks(tasks, userProfile, aiSnapshot) {
  const goalId = uuidv4(); // This will be both roadmap_id and goals.id
  const created_at = new Date();

  const client = await pool.getConnection();
  await client.beginTransaction();

  try {
    // 1. Insert into goals table FIRST (satisfies FK constraint)
    const insertGoalQuery = `
      INSERT INTO goals
        (id, user_id, title, description, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?)
    `;

    const goalTitle = aiSnapshot.title || "My Personalized Learning Roadmap";
    const goalDescription = "AI-generated roadmap based on skill level, tech stack, and goals";

    await client.query(insertGoalQuery, [
      goalId,
      userProfile.id,
      goalTitle,
      goalDescription,
      created_at,
      created_at,
    ]);

    // 2. Optional: Still save AI recommendation snapshot (good for history/debugging)
    const insertAiRecQuery = `
      INSERT INTO ai_recommendations
        (id, user_id, goal_snapshot, recommendation, reasoning, created_at)
      VALUES (?, ?, ?, ?, ?, ?)
    `;

    await client.query(insertAiRecQuery, [
      uuidv4(),
      userProfile.id,
      JSON.stringify(userProfile),
      JSON.stringify(aiSnapshot),
      "Auto-generated by Groq AI",
      created_at,
    ]);

    // 3. Insert all tasks
    const insertTaskQuery = `
      INSERT INTO tasks
        (id, goal_id, title, description, status, order_index, estimated_minutes, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `;

    for (const task of tasks) {
      await client.query(insertTaskQuery, [
        uuidv4(),
        goalId,                   // ← Now references existing goals.id
        task.title,
        task.description,
        "pending",
        task.order_index,
        task.estimated_minutes,
        created_at,
        created_at,
      ]);
    }

    await client.commit();

    return {
      roadmap_id: goalId,
      message: "Roadmap successfully generated and saved!",
    };
  } catch (error) {
    await client.rollback();
    console.error("Error persisting tasks:", error);
    throw new Error("Failed to save roadmap to database");
  } finally {
    client.release();
  }
}

export default persistTasks;